# Generated by Django 5.2.17 on 2026-09-30 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('IN_PERSON', 'In person'), ('ONLINE', 'Online')], default='IN_PERSON', max_length=10)),
                ('venue_or_link', models.CharField(blank=True, max_length=200)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_run', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.unit')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.classsession')),
            ],
            options={
                'ordering': ['student__first_name', 'student__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['unit', 'date'], name='attendance__unit_id_987d07_idx'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('unit', 'date', 'start_time'), name='unique_session_per_unit_slot'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='one_record_per_student_per_session'),
        ),
    ]
